
name: Delete PR env when PR is closed

on:
  pull_request:
    types: [closed]

concurrency: 
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

env:
  WEBAPP_NAME: tomcat-app
  RESOURCE_GROUP: freeberg-tomcat-slots-demo
  SLOT_NAME: pr-${{ github.event.number }}

jobs:
  delete-slot:

    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.ANTARES_BLOG_SITE_SP }}
    
    - name: Delete slot on staging site
      run: az webapp deployment slot delete --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME
