name: Release to prod

on:
  push:
    branches:
    - main

env:
  WEBAPP_NAME: tomcat-app
  RESOURCE_GROUP: freeberg-tomcat-slots-demo
  SLOT_NAME: staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft

    - name: Build app
      run: mvn clean package

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.war'
    
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app
    
    - name: Deploy to stage env
      uses: azure/webapps-deploy@v1
      id: deploy-to-webapp
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: '*.war'

    - name: Swap slots
      run: az deployment slot swap ...
