name: Deploy PR to staging env

on:
  pull_request:
    branches:
    - main

concurrency: ci-${{ github.event.number }}

env:
  WEBAPP_NAME: tomcat-app
  RESOURCE_GROUP: freeberg-tomcat-slots-demo
  SLOT_NAME: pr-${{ github.event.number }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft

    - name: Build app
      run: mvn clean package

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.war'
  
  set-up-staging-env:
    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create slot on staging site
      run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: [build, set-up-staging-env]
    permissions:
      pull-requests: write

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app

    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to slot on staging site
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: '*.war'
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.

          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
   